### ISSUE TITLE
dota2exe not found or not client dll

### ISSUE THREAD

**Issue by blurpijke** [F0RQU1N/external_patcher#2]
у меня есть проблема когда открываю выходит ошибка dota2exe not found or not client dll (I have a problem when I open it I get the issue dota2exe not found or not client dll)

**Comment by tranqu1lizer** [comment]
> у меня есть проблема когда открываю выходит ошибка dota2exe not found or not client dll (I have a problem when I open it I get the issue dota2exe not found or not client dll)

Просто сначала запускай игру)
