### ISSUE TITLE
Want Some new Features

### ISSUE THREAD

**Issue by khanshaib11** [F0RQU1N/external_patcher#3]
Hey dev thanks for the awesome cheat , can u also add the kill enemy nuker option where we can see if enemy is killable or not

**Comment by tranqu1lizer** [comment]
> Hey dev thanks for the awesome cheat , can u also add the kill enemy nuker option where we can see if enemy is killable or not

Hey, I think not because i will need to make damage calculation of the hero’s abilities. this program is game code patcher than a full cheat

**Comment by khanshaib11** [comment]
Thanks for the Replay so this external patcher is safe to use ? i am only using the first camera distance option also is all the 5 options are safe to use ?? .. Beside all these i really thank you for giving the program for free !!! Stay safe

**Comment by khanshaib11** [comment]
Can u add Weather changing and dotaplus or Match statistics feature ?? i am asking for to much sorry !!!!

**Comment by tranqu1lizer** [comment]
> Can u add Weather changing and dotaplus or Match statistics feature ?? i am asking for to much sorry !!!!

I'm working on it
